//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_Shipping.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Partes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Partes()
        {
            this.tbl_Estacion_Partes = new HashSet<tbl_Estacion_Partes>();
        }
    
        public int Id { get; set; }
        public string CMS { get; set; }
        public string Parte { get; set; }
        public int Fk_Proyecto { get; set; }
        public int Cant_Pzas { get; set; }
        public bool Estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Estacion_Partes> tbl_Estacion_Partes { get; set; }
        public virtual tbl_Proyectos tbl_Proyectos { get; set; }
    }
}
