//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_Shipping.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Estacion_Partes
    {
        public int Id { get; set; }
        public int Fk_Estacion { get; set; }
        public int Fk_Parte { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Estatus { get; set; }
    
        public virtual tbl_Estaciones tbl_Estaciones { get; set; }
        public virtual tbl_Partes tbl_Partes { get; set; }
    }
}
