//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_Shipping.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Seriales
    {
        public int Id { get; set; }
        public string Serial { get; set; }
        public string Proyecto { get; set; }
        public string Estacion { get; set; }
        public string Parte { get; set; }
        public int Turno { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Estatus { get; set; }
    }
}
